require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AssuntosController do

  # This should return the minimal set of attributes required to create a valid
  # Assunto. As you add validations to Assunto, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AssuntosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all assuntos as @assuntos" do
      assunto = Assunto.create! valid_attributes
      get :index, {}, valid_session
      assigns(:assuntos).should eq([assunto])
    end
  end

  describe "GET show" do
    it "assigns the requested assunto as @assunto" do
      assunto = Assunto.create! valid_attributes
      get :show, {:id => assunto.to_param}, valid_session
      assigns(:assunto).should eq(assunto)
    end
  end

  describe "GET new" do
    it "assigns a new assunto as @assunto" do
      get :new, {}, valid_session
      assigns(:assunto).should be_a_new(Assunto)
    end
  end

  describe "GET edit" do
    it "assigns the requested assunto as @assunto" do
      assunto = Assunto.create! valid_attributes
      get :edit, {:id => assunto.to_param}, valid_session
      assigns(:assunto).should eq(assunto)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Assunto" do
        expect {
          post :create, {:assunto => valid_attributes}, valid_session
        }.to change(Assunto, :count).by(1)
      end

      it "assigns a newly created assunto as @assunto" do
        post :create, {:assunto => valid_attributes}, valid_session
        assigns(:assunto).should be_a(Assunto)
        assigns(:assunto).should be_persisted
      end

      it "redirects to the created assunto" do
        post :create, {:assunto => valid_attributes}, valid_session
        response.should redirect_to(Assunto.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved assunto as @assunto" do
        # Trigger the behavior that occurs when invalid params are submitted
        Assunto.any_instance.stub(:save).and_return(false)
        post :create, {:assunto => {}}, valid_session
        assigns(:assunto).should be_a_new(Assunto)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Assunto.any_instance.stub(:save).and_return(false)
        post :create, {:assunto => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested assunto" do
        assunto = Assunto.create! valid_attributes
        # Assuming there are no other assuntos in the database, this
        # specifies that the Assunto created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Assunto.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => assunto.to_param, :assunto => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested assunto as @assunto" do
        assunto = Assunto.create! valid_attributes
        put :update, {:id => assunto.to_param, :assunto => valid_attributes}, valid_session
        assigns(:assunto).should eq(assunto)
      end

      it "redirects to the assunto" do
        assunto = Assunto.create! valid_attributes
        put :update, {:id => assunto.to_param, :assunto => valid_attributes}, valid_session
        response.should redirect_to(assunto)
      end
    end

    describe "with invalid params" do
      it "assigns the assunto as @assunto" do
        assunto = Assunto.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Assunto.any_instance.stub(:save).and_return(false)
        put :update, {:id => assunto.to_param, :assunto => {}}, valid_session
        assigns(:assunto).should eq(assunto)
      end

      it "re-renders the 'edit' template" do
        assunto = Assunto.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Assunto.any_instance.stub(:save).and_return(false)
        put :update, {:id => assunto.to_param, :assunto => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested assunto" do
      assunto = Assunto.create! valid_attributes
      expect {
        delete :destroy, {:id => assunto.to_param}, valid_session
      }.to change(Assunto, :count).by(-1)
    end

    it "redirects to the assuntos list" do
      assunto = Assunto.create! valid_attributes
      delete :destroy, {:id => assunto.to_param}, valid_session
      response.should redirect_to(assuntos_url)
    end
  end

end
